# Generated by Django 6.0.2 on 2026-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doer', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
