# Generated by Django 6.0.2 on 2026-03-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doer', '0005_doerprofile_doerskill_doerworkarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doerskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='doerskill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doerworkarea',
            name='place',
        ),
        migrations.RemoveField(
            model_name='doerworkarea',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoerProfile',
        ),
        migrations.DeleteModel(
            name='DoerSkill',
        ),
        migrations.DeleteModel(
            name='DoerWorkArea',
        ),
    ]
