# Generated by Django 6.0.2 on 2026-03-11 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_category_skill'),
        ('doer', '0006_remove_doerskill_skill_remove_doerskill_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doer_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoerWorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.pincode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doer_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
