# Generated by Django 6.0.2 on 2026-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pincode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
        migrations.RenameField(
            model_name='pincode',
            old_name='code',
            new_name='pincode_number',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='place_name',
        ),
        migrations.AlterUniqueTogether(
            name='pincode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='district',
            name='name',
        ),
        migrations.AddField(
            model_name='district',
            name='district_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='pincode',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
