# Generated by Django 6.0.2 on 2026-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_live_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification/live_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
