# Generated by Django 6.0.2 on 2026-02-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verification_live_photo_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approval_status',
            field=models.CharField(default='Rejected', max_length=20),
        ),
    ]
