# Generated by Django 6.0.2 on 2026-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adhar_card',
        ),
        migrations.AddField(
            model_name='user',
            name='adhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='adhar_photos/'),
        ),
    ]
