# Generated by Django 6.0.2 on 2026-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_adhar_card_user_adhar_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
