# Generated by Django 6.0.2 on 2026-02-25 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0003_category_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_at', models.DateTimeField()),
                ('deadline_datetime', models.DateTimeField()),
                ('doer_completion_estimate', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.district')),
                ('doer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_accepted', to=settings.AUTH_USER_MODEL)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_posted', to=settings.AUTH_USER_MODEL)),
                ('pincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.pincode')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.place')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.skill')),
            ],
        ),
    ]
