# Generated by Django 6.0.2 on 2026-02-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='doer_completion_estimate',
        ),
        migrations.AlterField(
            model_name='task',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
