# Generated by Django 6.0.2 on 2026-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0005_taskinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Open', max_length=30),
        ),
    ]
