# Generated by Django 6.0.2 on 2026-03-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giver', '0006_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskInvitation',
        ),
    ]
